#!/bin/bash

TREE=$PWD/root

PATH=$TREE/bin:$PATH
LD_LIBRARY_PATH=$TREE/lib

LUA_PATH="./?.lua"
LUA_PATH="$LUA_PATH;$TREE/share/luajit-2.1.0-beta3/?.lua"
LUA_PATH="$LUA_PATH;$TREE/share/lua/5.1/?.lua;$TREE/share/lua/5.1/?/init.lua"

LUA_CPATH="./?.so"
LUA_CPATH="$LUA_CPATH;$TREE/lib/lua/5.1/?.so"
LUA_CPATH="$LUA_CPATH;$TREE/lib/lua/5.1/loadall.so"

LUAROCKS="luarocks --lua-version 5.1 --lua-dir $TREE --tree $TREE"

export TREE
export PREFIX
export PATH
export LUA_PATH
export LUA_CPATH
